checks:
  php: true

filter:
  paths:
    - src/

build:
  image: default-bionic

  environment:
    php:
      version: 8.1

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
